python finetune_llama.py \
    --base_model 'decapoda-research/llama-7b-hf' \
    --data_path 'data/expla_graph_predict_stance_train.json' \
    --output_dir './explagraph-llama-7b-sft' \
    --batch_size 128 \
    --micro_batch_size 16 \
    --num_epochs 5 \
    --learning_rate 3e-4 \
    --cutoff_len 512 \
    --val_set_size 168 \
    --lora_r 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --lora_target_modules '[q_proj,v_proj]' \
    --train_on_inputs \
    --group_by_length \
